### ISSUE TITLE
Create Homepage

### ISSUE THREAD

**Issue by Faizaliso** [Faizaliso/ascendancy#1]
- [ ] Install PrismaORM & Configure sesuai ERD
- [ ] Membuat Homepage
- [ ] Membuat single page event

**Comment by arifskd** [comment]
![Screenshot_2024-06-27_11-02-03](https://github.com/Faizaliso/ascendancy/assets/169121007/6a1f103c-79d8-4a6b-8d69-437c8e7f6d2f)

**Comment by arifskd** [comment]
![Lokakarya_2024-06-25T14_53_22 421Z](https://github.com/Faizaliso/ascendancy/assets/169121007/2181734f-bb2d-4429-ac07-f9ad37aa483e)
